### ISSUE TITLE
XX-Net-mini-4.5.2 提示缺少CA.crt

### ISSUE THREAD

**Issue by goxp49** [miketwes/XX-Net-mini#12]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\XX-Net-mini-4.5.2\\data\\gae_proxy\\CA.crt'
看了下目录里确实没这个文件，请问要在哪下？

**Comment by miketwes** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'D:\XX-Net-mini-4.5.2\data\gae_proxy\CA.crt'
> 看了下目录里确实没这个文件，请问要在哪下？

这个应该是在Windows下安装openssl后没有添加环境变量,  添加环境变量后再运行start.bat

**Comment by goxp49** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: 'D:\XX-Net-mini-4.5.2\data\gae_proxy\CA.crt'
> > 看了下目录里确实没这个文件，请问要在哪下？
> 
> 这个应该是在Windows下安装openssl后没有添加环境变量, 添加环境变量后再运行start.bat

确实是这样，添加变量后已经OK，感谢！

**Comment by masktao** [comment]
> > FileNotFoundError: [Errno 2] No such file or directory: 'D:\XX-Net-mini-4.5.2\data\gae_proxy\CA.crt'
> > 看了下目录里确实没这个文件，请问要在哪下？
> 
> 这个应该是在Windows下安装openssl后没有添加环境变量, 添加环境变量后再运行start.bat
还要安装openssl吗?不是目录就有吗?不是绿色运行吗?
环境变量是啥?
