### ISSUE TITLE
关于删掉的内容，是我没讲清楚造成了误会

### ISSUE THREAD

**Issue by SeaHOH** [miketwes/XX-Net-mini#5]
之前说删，指的是 issue comment，没想到你把数据本身都删掉了。。。
我只是不想在 XX-Net 那里吸引到太多小白，对付他们真的不容易，尤其是与 GotoX 的目标用户相差太大，绝大部分也不可能转化过来，结果剩下的就是混乱。

本来就是开源，我是不可能反对有人维护数据和配置的更新。
不过你这里删掉了也好，现在有两个方式可以选择继续：
- 你新建或 fork 个仓库，不然文不对题，之前看起来确实有点怪怪的。
- 也欢迎你直接向 GotoX 提 PR，不止是数据和配置，其它都可以。大欢迎！

总而言之，不好意思哈，让你误会了，希望你不要介意。 :handshake:

**Comment by miketwes** [comment]
怎么会介意呢 :handshake:

**Comment by daxinnan** [comment]
haha，我在老铁删除之前先clone了 @miketwes 的仓库，现在可以自由浏览了，有一个问题是如果要使用新申请的appid是要先在xx-net上部署之后在gotoX项目里应用还是可以直接应用在GotoX的Config.ini里面呢？谢谢两位大神的维护和更新

**Comment by miketwes** [comment]
新申请的appid要先部署服务端

**Comment by miketwes** [comment]
> haha，我在老铁删除之前先clone了 @miketwes 的仓库，现在可以自由浏览了，有一个问题是如果要使用新申请的appid是要先在xx-net上部署之后在gotoX项目里应用还是可以直接应用在GotoX的Config.ini里面呢？谢谢两位大神的维护和更新

新申请的appid要先部署服务端

**Comment by daxinnan** [comment]
> > haha，我在老铁删除之前先clone了 @miketwes 的仓库，现在可以自由浏览了，有一个问题是如果要使用新申请的appid是要先在xx-net上部署之后在gotoX项目里应用还是可以直接应用在GotoX的Config.ini里面呢？谢谢两位大神的维护和更新
> 
> 新申请的appid要先部署服务端

python2 uploader.py上传gae server是不是就是部署服务端的操作呀，还是说appid只能先在xx-net里部署

**Comment by miketwes** [comment]
> > > haha，我在老铁删除之前先clone了 @miketwes 的仓库，现在可以自由浏览了，有一个问题是如果要使用新申请的appid是要先在xx-net上部署之后在gotoX项目里应用还是可以直接应用在GotoX的Config.ini里面呢？谢谢两位大神的维护和更新
> > 
> > 
> > 新申请的appid要先部署服务端
> 
> python2 uploader.py上传gae server是不是就是部署服务端的操作呀，还是说appid只能先在xx-net里部署

python2 uploader.py上传gae server就是部署服务端的操作, 也可以用Google Cloud部署:

![2019-02-20_563x112](https://user-images.githubusercontent.com/6849681/53083388-ccfc3700-3539-11e9-99f3-bc48321c7275.png)

![2019-02-20_180x219](https://user-images.githubusercontent.com/6849681/53083197-5fe8a180-3539-11e9-938f-b5d98177b37c.png)

**Comment by daxinnan** [comment]
好的，谢谢您～救活了我哈哈
