### ISSUE TITLE
证书咋不对的？

### ISSUE THREAD

**Issue by snipertulip** [miketwes/XX-Net-mini#9]
Your connection is not private
Attackers might be trying to steal your information from www.google.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_AUTHORITY_INVALID

Help improve security on the web for everyone by sending URLs of some pages you visit, limited system information, and some page content to Google. Privacy policy

**Comment by miketwes** [comment]
将XX-Net-mini/data/gae_proxy/CA.crt导入到系统后, 再将XX-Net-mini/data/gae_proxy/CA.crt导入到浏览器
